name: Rust

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NINJA_PATH: ~/ninja-build
      PICO_SDK_PATH: ~/pico-sdk
      PICO_EXTRAS_PATH: ~/pico-extras

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: pico-sdk-cache
        with:
          path: |
            ${{ env.PICO_SDK_PATH }}
            ${{ env.PICO_EXTRAS_PATH }}
          key: pico-sdk

      - uses: actions/cache@v4
        id: ninja-cache
        with:
          path: ${{ env.NINJA_PATH }}
          key: pico-sdk

      - name: Add thumbv6m-none-eabi target
        run: rustup target add thumbv6m-none-eabi

      - name: Setup GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.2
        id: arm-none-eabi-gcc-action
      - run: export PICO_TOOLCHAIN_PATH="${{ steps.arm-none-eabi-gcc-action.outputs.path }}"

      - name: Setup ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5
        with:
          destination: ${{ env.NINJA_PATH }}

      - name: Clone Pico SDK and extras
        if: steps.pico-sdk-cache.outputs.cache-hit != 'true'
        run: |
          git clone --recurse https://github.com/raspberrypi/pico-sdk.git $PICO_SDK_PATH
          git clone --recurse https://github.com/raspberrypi/pico-extras.git $PICO_EXTRAS_PATH

      - name: Build
        run: cargo build --verbose --release
